update files

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -202,18 +202,6 @@ runs:
       labels: |
         org.opencontainers.image.version=${{ env.TAG }}
 
-  # - name: Gerando Tags e Labels para usar na imagem Supervisor
-  #   id: meta_supervisor
-  #   uses: docker/metadata-action@v4
-  #   with:
-  #     images: ${{ inputs.ECR_REGISTRY }}/${{ inputs.SUPERVISOR_IMAGE_NAME }}
-  #     flavor: latest=true
-  #     tags: |
-  #       type=raw,value=${{ env.TAG }}
-  #       type=sha,format=long,prefix=
-  #     labels: |
-  #       org.opencontainers.image.version=${{ env.TAG }}
-
   - name: Build e Push da Imagem Docker (se aplicável)
     if: ${{ inputs.DOCKERFILE_PATH != '' }}
     uses: docker/build-push-action@v3
@@ -228,28 +216,6 @@ runs:
       no-cache: true
       build-args: |
         IMAGE=${{ inputs.BASE_IMAGE }}
-
-  # - name: Build e Push da Imagem Docker (logos-supervisor)
-  #   if: ${{ inputs.SUPERVISOR_DOCKERFILE_PATH != '' }}
-  #   uses: docker/build-push-action@v3
-  #   with:
-  #     context: .
-  #     file: ${{ inputs.SUPERVISOR_DOCKERFILE_PATH }}
-  #     tags: |
-  #       ${{ inputs.ECR_REGISTRY }}/${{ inputs.SUPERVISOR_IMAGE_NAME }}:${{ env.TAG }}
-  #       ${{ steps.meta_supervisor.outputs.tags }}
-  #     labels: ${{ steps.meta_supervisor.outputs.labels }}
-  #     push: true
-  #     no-cache: true
-  #     build-args: |
-  #       IMAGE=${{ inputs.SUPERVISOR_BASE_IMAGE }}
-
-  - name: Exportando Summary
-    run: |
-      echo "### Image tag :framed_picture:" >> $GITHUB_STEP_SUMMARY
-      # echo "$GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
-      echo "${{ env.TAG }}" >> $GITHUB_STEP_SUMMARY
-    shell: bash
 
   # ##################  DEPLOY IMAGE # ##################
 
@@ -390,237 +356,66 @@ runs:
         echo "EC2_IPS_COMMA=${{ env.EC2_IPS }}" >> $GITHUB_ENV
       fi
 
-  - name: Manipulando tag nova no manifestos
-    uses: appleboy/ssh-action@master
-    with:
-      username: ${{ inputs.SSH_USER }}
-      key_path: ssh_key.pem
-      host: ${{ env.EC2_IPS_COMMA }}
-      script: |
-        set -e
-        tar -xzf /tmp/deploy.tar.gz -C /tmp/
-        export GITHUB_COMMIT=${{ env.TAG }}
-        BRANCH_NAME="rc/$GITHUB_COMMIT"
+  - name: Executando comandos remotos nas instâncias EC2 por nome
+    shell: bash
+    run: |
+      IFS=' ' read -r -a IPS <<< "${EC2_IPS}"
+      IFS=' ' read -r -a NAMES <<< "${{ inputs.SERVER_LIST }}"
 
-        cd /home/ubuntu/log-os/
+      if [ "${#IPS[@]}" -ne "${#NAMES[@]}" ]; then
+        echo "::error::Quantidade de IPs e nomes de instância não correspondem!"
+        exit 1
+      fi
 
-        echo "Baixando todas as branches e tags remotas..."
-        git fetch --all --prune
+      for i in "${!IPS[@]}"; do
+        IP="${IPS[$i]}"
+        NAME="${NAMES[$i]}"
+        echo "Conectando na instância: $NAME ($IP)..."
 
-        echo "Commitando mudanças antes de trocar para $BRANCH_NAME..."
-        git config --global user.email "github-actions@github.com"
-        git config --global user.name "GitHub Actions"
-        git add .
-        git commit -m "Atualização automática do Dockerfile antes de trocar para a branch $BRANCH_NAME" || echo "Nenhuma mudança para commit."
+        COMPOSE_PATH=""
+        BRANCH_NAME="${{ env.TAG }}"
 
-        if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null; then
-            echo "Trocando para a branch $BRANCH_NAME..."
-            git checkout "$BRANCH_NAME"
-            git reset --hard origin/$BRANCH_NAME
-            git pull origin "$BRANCH_NAME"
-        else
-            echo "Erro: A branch '$BRANCH_NAME' não existe remotamente."
+        if [[ "$BRANCH_NAME" == rc* ]]; then
+          COMPOSE_PATH="/tmp/deploy/.infra/homol/docker-compose.yml"
+        elif [[ "$BRANCH_NAME" == main* ]]; then
+          if [[ "$NAME" == *celery* ]]; then
+            COMPOSE_PATH="/tmp/deploy/.infra/prod/celery/docker-compose.yml"
+          elif [[ "$NAME" == *flower* ]]; then
+            COMPOSE_PATH="/tmp/deploy/.infra/prod/flower/docker-compose.yml"
+          elif [[ "$NAME" == *api* ]]; then
+            COMPOSE_PATH="/tmp/deploy/.infra/prod/api/docker-compose.yml"
+          else
+            echo "::error::Instância $NAME não reconhecida para produção."
             exit 1
-        fi
-
-        # Substituir :latest pela nova tag
-        find /tmp/deploy -type f -name 'Dockerfile' -exec sed -i "s|:latest|:${GITHUB_COMMIT}|g" {} +
-
-        # Determinar o diretório correto
-        TARGET_DIR="/home/ubuntu/log-os/.infra/homol"
-        if [[ "$BRANCH_NAME" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
-          echo "Branch é 'main', alterando destino para infra/prod..."
-          TARGET_DIR="/home/ubuntu/log-os/.infra/prod"
-        fi
-
-        mkdir -p "$TARGET_DIR/php"
-        mkdir -p "$TARGET_DIR/supervisor"
-
-        # Mover os Dockerfiles e compose corrigido
-        mv /tmp/deploy/.infra/homol/php/Dockerfile "$TARGET_DIR/php/Dockerfile"
-        mv /tmp/deploy/.infra/homol/supervisor/Dockerfile "$TARGET_DIR/supervisor/Dockerfile"
-        mv /tmp/deploy/.infra/homol/docker-compose.yml "$TARGET_DIR/docker-compose.yml"
-
-  - name: Subindo nova tag
-    uses: appleboy/ssh-action@master
-    with:
-      username: ${{ inputs.SSH_USER }}
-      key_path: ssh_key.pem
-      host: ${{ env.EC2_IPS_COMMA }}
-      script: |
-        set -e  # Encerra o script se qualquer comando falhar
-
-        # Definir diretórios padrão para ambiente HOMOL
-        ENV_PATH="/home/ubuntu/log-os/.env"
-        S3_ENV_PATH="s3://logcomex-environments-files/log-os/.env.homol"
-        COMPOSE_DIR="/home/ubuntu/log-os/.infra/homol"
-
-        # Se estiver na branch main, usar ambiente PROD
-        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-          echo "Branch é 'main', alterando para ambiente de produção..."
-          S3_ENV_PATH="s3://logcomex-environments-files/log-os/.env.prod"
-          COMPOSE_DIR="/home/ubuntu/log-os/.infra/prod/php"
-        fi
-
-        echo "Baixando o arquivo de ambiente do S3..."
-        if aws s3 ls "$S3_ENV_PATH" > /dev/null 2>&1; then
-          aws s3 cp "$S3_ENV_PATH" "$ENV_PATH"
+          fi
         else
-          echo "Erro: O arquivo $S3_ENV_PATH não foi encontrado no S3."
+          echo "::error::Branch inválida: $BRANCH_NAME"
           exit 1
         fi
 
-        echo "Entrando no diretório da infraestrutura..."
-        if [ -d "$COMPOSE_DIR" ]; then
-          cd "$COMPOSE_DIR"
-        else
-          echo "Erro: O diretório $COMPOSE_DIR não existe."
-          exit 1
-        fi
+        echo "Rodando docker-compose com arquivo: $COMPOSE_PATH"
 
-        echo "Recriando os containers com Docker Compose..."
-        docker-compose up -d --force-recreate
+        ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$IP" \
+          "set -e && \
+          echo 'Descompactando deploy.tar.gz...' && \
+          tar -xzf /tmp/deploy.tar.gz -C /tmp/ && \
+          export GITHUB_COMMIT='${{ env.TAG }}' && \
+          echo 'Atualizando Dockerfiles...' && \
+          find /tmp/deploy -type f -name 'Dockerfile' -exec sed -i \"s|:latest|:\$GITHUB_COMMIT|g\" {} + && \
+          echo 'Executando docker-compose...' && \
+          docker-compose -f $COMPOSE_PATH up -d --build && \
+          echo 'Limpando arquivos temporários...' && \
+          rm -rf /tmp/deploy /tmp/deploy.tar.gz" || {
+            echo "::error::Erro ao executar comandos na instância $NAME ($IP)"
+            exit 1
+          }
 
-        echo "Aguardando container logos-app iniciar..."
-        sleep 5  # Ajuste se necessário para garantir que o container esteja rodando
-
-        echo "Verificando se o container logos-app está rodando..."
-        if docker ps --format '{{.Names}}' | grep -q "logos-app"; then
-          echo "Copiando arquivo .env para dentro do container logos-app..."
-          docker cp "$ENV_PATH" logos-app:/var/www/.env
-        else
-          echo "Erro: O container logos-app não está rodando. Não foi possível copiar o .env."
-          exit 1
-        fi
-
-        echo "Processo finalizado com sucesso."
-
-  - name: Definir variável do nome do arquivo
-    shell: bash
-    run: |
-      export S3_FILE="builds/build-$(date +%Y%m%d%H%M%S).tar.gz"
-      echo "S3_FILE=$S3_FILE" >> $GITHUB_ENV
-      echo "Nome do arquivo para upload e download: $S3_FILE"
-
-  - name: Preparando build na instância primária e enviando para o S3
-    shell: bash
-    run: |
-      PRIMARY_HOST=$(echo "${{ env.EC2_IPS_COMMA }}" | awk -F',' '{print $1}' | tr -d ' ')
-      S3_BUCKET="log-os-publish-artifacts"
-
-      echo "PRIMARY_HOST: $PRIMARY_HOST"
-      echo "Upload para S3: s3://$S3_BUCKET/${{ env.S3_FILE }}"
-
-      ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$PRIMARY_HOST" \
-      "set -e && \
-      echo 'Rodando build do Node.js na instância primária ($PRIMARY_HOST)...' && \
-      docker exec logos-app npm install --silent && \
-      docker exec logos-app npm run build && \
-      docker exec logos-app tar -czf /tmp/build.tar.gz public && \
-      docker cp logos-app:/tmp/build.tar.gz /tmp/build.tar.gz && \
-      echo 'Build finalizado e copiado para a instância primária.'"
-
-      echo "Fazendo upload do build para o S3..."
-      ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$PRIMARY_HOST" \
-      "aws s3 cp /tmp/build.tar.gz s3://$S3_BUCKET/${{ env.S3_FILE }} --acl private"
-
-      echo "Upload para S3 concluído: s3://$S3_BUCKET/${{ env.S3_FILE }}"
+        echo "Deploy finalizado para $NAME ($IP)"
+      done
 
   - name: Configurar permissões da chave SSH
     shell: bash
     run: chmod 600 ssh_key.pem
-
-  - name: Distribuir build para outras instâncias
-    shell: bash
-    run: |
-      PRIMARY_HOST=$(echo "${{ env.EC2_IPS_COMMA }}" | awk -F',' '{print $1}' | tr ',' ' ')
-      OTHER_HOSTS=$(echo "${{ env.EC2_IPS_COMMA }}" | sed "s/$PRIMARY_HOST,//" | tr ',' ' ')
-      S3_BUCKET="log-os-publish-artifacts"
-
-      if [ -z "$OTHER_HOSTS" ]; then
-        echo "Não há outras instâncias para copiar o build. Finalizando."
-        exit 0
-      fi
-
-      echo "PRIMARY_HOST: $PRIMARY_HOST"
-      echo "Outras instâncias: $OTHER_HOSTS"
-      echo "Baixando do S3: s3://$S3_BUCKET/${{ env.S3_FILE }}"
-
-      for HOST in $OTHER_HOSTS; do
-        echo "Baixando build do S3 em $HOST..."
-        ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$HOST" \
-        "aws s3 cp s3://$S3_BUCKET/${{ env.S3_FILE }} /tmp/build.tar.gz && \
-        echo 'Arquivo baixado do S3.'"
-
-        echo "Removendo arquivos antigos antes da extração..."
-        ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$HOST" \
-        "docker exec logos-app rm -rf /var/www/public/*"
-
-        echo "Copiando build para o contêiner logos-app em $HOST..."
-        ssh -o StrictHostKeyChecking=no -i ssh_key.pem "${{ inputs.SSH_USER }}@$HOST" \
-        "docker cp /tmp/build.tar.gz logos-app:/tmp/build.tar.gz && \
-        docker exec logos-app tar -xzf /tmp/build.tar.gz -C /var/www/public --strip-components=1 && \
-        docker exec logos-app rm /tmp/build.tar.gz && \
-        docker exec logos-app chown -R www-data:www-data /var/www/public"
-
-        echo "Build atualizado corretamente em $HOST na pasta /var/www/public!"
-      done
-
-  - name: Preparando ambiente pós new tag
-    uses: appleboy/ssh-action@master
-    with:
-      username: ${{ inputs.SSH_USER }}
-      key_path: ssh_key.pem
-      host: ${{ env.EC2_IPS_COMMA }}
-      script: |
-        set -e
-
-        echo "Ajustando permissões e rodando otimizações..."
-        docker exec logos-app chown www-data:www-data bootstrap/cache -R
-
-        if [ "${GITHUB_REF_NAME}" = "main" ]; then
-          echo "Branch 'main' detectada. Rodando em todos os containers..."
-          docker exec logos-app composer install --no-interaction --prefer-dist --optimize-autoloader
-          docker exec logos-reverb composer install --no-interaction --prefer-dist --optimize-autoloader
-          docker exec logos-supervisor composer install --no-interaction --prefer-dist --optimize-autoloader
-        else
-          echo "Branch '${GITHUB_REF_NAME}' detectada. Rodando apenas no logos-app..."
-          docker exec logos-app composer install --no-interaction --prefer-dist --optimize-autoloader
-        fi
-
-        docker exec logos-app php artisan config:cache
-        docker exec logos-app php artisan view:cache
-        docker exec logos-app chown www-data:www-data storage -R
-
-        echo "Processo concluído com sucesso."
-
-  # - name: Rebuild supervisor
-  #   uses: appleboy/ssh-action@master
-  #   with:
-  #     username: ${{ inputs.SSH_USER }}
-  #     key_path: ssh_key.pem
-  #     host: ${{ env.EC2_IPS_COMMA }}
-  #     script: |
-  #       set -e
-
-  #       # Determina o caminho com base na branch
-  #       if [ "${GITHUB_REF_NAME}" = "main" ]; then
-  #         COMPOSE_DIR="log-os/.infra/prod/supervisor"
-  #       else
-  #         COMPOSE_DIR="log-os/.infra/homol/supervisor"
-  #       fi
-
-  #       cd $COMPOSE_DIR
-
-  #       if docker ps --format '{{.Names}}' | grep -q '^logos-supervisor$'; then
-  #         echo "Container logos-supervisor encontrado. Executando composer install e recriando container..."
-
-  #         docker exec logos-supervisor composer install --no-interaction --prefer-dist --optimize-autoloader
-
-  #         docker-compose up -d --force-recreate
-  #       else
-  #         echo "Container logos-supervisor não encontrado. Nada será feito."
-  #       fi
 
   - name: Encerrando a VPN (se aplicável)
     if: always() && inputs.OVPN_CONFIG_FILE != ''
